### ISSUE TITLE
add_cumulaitve() throwing error

### ISSUE THREAD

**Issue by jaliasd** [ICPI/ICPIutilities#30]
Know we know about the `fy2018cum` but not sure if the glue issue was known or not
`
Error: Unknown column `fy2018cum` 
In addition: Warning message:
'glue::collapse' is deprecated.
Use 'glue_collapse' instead.
See help("Deprecated") and help("glue-deprecated"). 
`

**Comment by achafetz** [comment]
@jaliasd what version of glue do you have? 

`packageVersion("glue")` 

The one on my machine appears to be 1.3.0 so maybe its a versioning issue? If so I can add the specific glue version to the package dependencies. 

Scary as it sounds, I'm not sure how this is an issue since I don't use glue anywhere (but my guess is `dplyr::full_join()` uses it as a dependency)

**Comment by achafetz** [comment]
relates to #23

**Comment by achafetz** [comment]
Issue is what is laid out in the [orientation material rmd](https://github.com/ICPI/ICPIutilities/blob/master/Orientation_Materials/ICPIutilities_showntell.md#combine_netnew)

> The functions spits back an error here since it doesn't know how to handle the cumulative value we added with the last function. This issue is likely a bug I can work out in the future but I wanted to demonstrate the error message. If you think about it though, the logical flow should be to add net new on before you create a cumulative value.
